repos:
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
    -   id: doctoc
-   repo: local
    hooks:
      - id: contents-aggregator
        name: contents-aggregator
        entry: "python ./contents-composite.py"
        language: python
        args: [--output, contents.txt, --depth, "5"]