repos:
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
    -   id: doctoc
-   repo: https://github.com/M-Astrid/path-pixie
    rev: 0.2.0
    hooks:
      - id: path-pixie
        name: path-pixie
        args: [--output, readme.md, --depth, "5", --root, "knowledge_base", --prefix, "emoji"]