repos:
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
    -   id: doctoc
-   repo: local
    hooks:
      - id: my-custom-sort
        name: Мой собственный сортировщик импортов
        entry: ./contents-composite.py
        language: script
        files: \.py$